CREATE TABLE accolades
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accolade     VARCHAR(100)                            NOT NULL,
    organization VARCHAR(100)                            NOT NULL,
    description  VARCHAR(1000),
    issue_date   date,
    CONSTRAINT pk_accolades PRIMARY KEY (id)
);

CREATE TABLE educations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    degree      VARCHAR(100)                            NOT NULL,
    school      VARCHAR(100)                            NOT NULL,
    gpa         FLOAT,
    start_date  date,
    end_date    date,
    description VARCHAR(1000),
    is_present  BOOLEAN,
    CONSTRAINT pk_educations PRIMARY KEY (id)
);

CREATE TABLE experiences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(100)                            NOT NULL,
    company         VARCHAR(100)                            NOT NULL,
    employment_type VARCHAR(100)                            NOT NULL,
    location        VARCHAR(100),
    description     VARCHAR(1000),
    start_date      date,
    end_date        date,
    is_present      BOOLEAN,
    CONSTRAINT pk_experiences PRIMARY KEY (id)
);

CREATE TABLE objectives
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objective VARCHAR(500),
    CONSTRAINT pk_objectives PRIMARY KEY (id)
);

CREATE TABLE profiles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_image VARCHAR(1000),
    first_name    VARCHAR(100)                            NOT NULL,
    last_name     VARCHAR(100)                            NOT NULL,
    email         VARCHAR(100)                            NOT NULL,
    phone_number  VARCHAR(20),
    address       VARCHAR(100),
    city          VARCHAR(100),
    zip_code      VARCHAR(10),
    country       VARCHAR(100),
    nationality   VARCHAR(100),
    birthdate     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE pursuits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pursuit VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_pursuits PRIMARY KEY (id)
);

CREATE TABLE referees
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name    VARCHAR(100)                            NOT NULL,
    relationship VARCHAR(100),
    job_title    VARCHAR(100)                            NOT NULL,
    company      VARCHAR(100),
    CONSTRAINT pk_referees PRIMARY KEY (id)
);

CREATE TABLE resumes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_resumes PRIMARY KEY (id)
);

CREATE TABLE skills
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    skill VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_skills PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(100)                            NOT NULL,
    surname  VARCHAR(100)                            NOT NULL,
    email    VARCHAR(100)                            NOT NULL,
    password VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);